FROM node:12-alpine AS BUILD_IMAGE

# install next-optimized-images requirements
RUN apk --no-cache update \ 
    && apk --no-cache add yarn curl g++ make bash zlib-dev libpng-dev \
    &&  rm -fr /var/cache/apk/*

WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn --frozen-lockfile

FROM node:12-alpine

WORKDIR /app

COPY . .

# copy from build image
COPY --from=BUILD_IMAGE /app/node_modules ./node_modules

ENV NODE_ENV=development

ENTRYPOINT [ "yarn", "dev" ]